### ISSUE TITLE
HB权限问题

### ISSUE THREAD

**Issue by king-zhangbn** [dulaiduwang003/cogni-comfyui-openrouter-ai#2]
<img width="1943" alt="image" src="https://user-images.githubusercontent.com/60092461/223123952-063844d6-0984-469a-b897-36a3e629784f.png">
[HBuilder] 21:29:30.118 项目 'chatgpt' 开始发布微信小程序...
[HBuilder] 21:29:30.488 此应用 DCloud appid 为 __UNI__32C6F91 ，您不是这个应用的项目成员。1、联系这个应用的所有者，请求加入项目成员（https://dev.dcloud.net.cn "成员管理"-"添加项目成员"）；2、重新在manifest.json中生成自己的APPID；3、联系应用所有者将此 DCloud appid 转让给当前账号。
[HBuilder] 21:29:30.497 项目 'chatgpt' 发布微信小程序失败.

**Comment by dulaiduwang003** [comment]
重新生成Cloud账号即可
